# application: b3ful68
# version: cdxdnd-v1

runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|js|css))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /
  script: index.php

- url: /admin/
  script: admin/index.php

- url: /admin/control_panel.php
  script: admin/control_panel.php


- url: /admin/index.php
  script: admin/index.php

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/b3ful68:us-central1:ksmysql;dbname=xdndedusql1
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  